springdoc:
  swagger-ui:
    path: /index.html
    persist-authorization: true
  packages-to-scan: org.example.mollyapi

spring:
  profiles:
    include: secret

mybatis:
  mapper-locations: classpath:mapper/*.xml  # MyBatis XML 매퍼 파일 위치
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus