springdoc:
  swagger-ui:
    path: /index.html
    persist-authorization: true
  packages-to-scan: org.example.mollyapi

spring:
  profiles:
    include: secret

---
spring:
  config:
    activate:
      on-profile: test