password:
  encode:
    algorithm: PBKDF2WithHmacSHA1
    iterations: 8524
    keyLength: 128
    saltAlgorithm: SHA-256

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://221.145.75.81:3306/molly
    username: molly
    password: 5Molly!@#3

jjwt:
  secret-key: YghJQDCgYOLtTKHH8TLtLdT9GaWQxE40ITOsGjGnc0Y=
  expiration-time: 3600000